name: Build Wheels OSX

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
          - python-version: 3.6
            PYTHON_VERSION_CODE: cp36-cp36m
            PYTHON_VERSION_NUMBER: 3.6
            PYTHON: /opt/python/cp36-cp36m/bin/python3.6
            PYTHON_PATH: /opt/python/cp36-cp36m/bin/
            PYTHON_INCLUDE: /opt/python/cp36-cp36m/include/python3.6m/
            PYTHON_LIB: /opt/python/cp36-cp36m/lib/python3.6
          - python-version: 3.7
            PYTHON_VERSION_CODE: cp37-cp37m
            PYTHON_VERSION_NUMBER: 3.7
            PYTHON: /opt/python/cp37-cp37m/bin/python3.7
            PYTHON_PATH: /opt/python/cp37-cp37m/bin/
            PYTHON_INCLUDE: /opt/python/cp37-cp37m/include/python3.7m/
            PYTHON_LIB: /opt/python/cp37-cp37m/lib/python3.7
          - python-version: 3.8
            PYTHON_VERSION_CODE: cp38-cp38
            PYTHON_VERSION_NUMBER: 3.8
            PYTHON: /opt/python/cp38-cp38/bin/python3.8
            PYTHON_PATH: /opt/python/cp38-cp38/bin/
            PYTHON_INCLUDE: /opt/python/cp38-cp38/include/python3.8/
            PYTHON_LIB: /opt/python/cp38-cp38/lib/python3.8
          - python-version: 3.9
            PYTHON_VERSION_CODE: cp39-cp39
            PYTHON_VERSION_NUMBER: 3.9
            PYTHON: /opt/python/cp39-cp39/bin/python3.9
            PATH_PATH: /opt/python/cp39-cp39/bin/
            PYTHON_INCLUDE: /opt/python/cp39-cp39/include/python3.9/
            PYTHON_LIB: /opt/python/cp39-cp39/lib/python3.9
    name: OSX wheel for Python ${{ matrix.python-version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Select Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Set variables
        run: |
          VER=$(cat ./VERSION.txt)
          echo "VERSION=$VER"
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Test environment
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "PYTHON_VERSION_CODE=${{ matrix.PYTHON_VERSION_CODE }}"
          echo "PYTHON_VERSION_NUMBER=${{ matrix.PYTHON_VERSION_NUMBER }}"
      - name: Install pytest, wheel and auditwheel
        run: ${{ matrix.PYTHON }} -m pip install pytest wheel auditwheel
      - name: Install dependencies
        run: ci/mac/install_dependencies.sh
      - name: Build wheel
        run: |
          cd ci/mac
          ./build_wheels.sh
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-macosx_10_14_x86_64.whl
          path: wheelhouse/nimblephysics-${{ env.VERSION }}-${{ matrix.PYTHON_VERSION_CODE }}-macosx_10_14_x86_64.whl
