name: Build Wheels

jobs:
  build:
    runs-on: ubuntu-latest
    container: keenon/diffdart:base
    strategy:
      matrix:
        python-version: ["pypy-3.6", "pypy-3.7", "pypy-3.8", "pypy-3.9"]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Pybind11 for this Python version
        run: git clone https://github.com/pybind/pybind11.git &&
          pushd pybind11 &&
          mkdir build &&
          pushd build &&
          cmake .. &&
          make install -j2
      - name: Install pytest and auditwheel
        run: python -m pip install pytest auditwheel
      - name: Build wheel
        run: python setup.py sdist bdist_wheel &&
          python -m auditwheel repair dist/nimblephysics-${{ env.version }}-${{ matrix.python-version }}-linux_x86_64.whl
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: nimblephysics-${{ env.version }}-${{ matrix.python-version }}-manylinux
          path: /nimblephysics/wheelhouse/nimblephysics-${{ env.version }}-${{ matrix.python-version }}-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
